### ISSUE TITLE
[feat] 필터구현 및 조회수 증가 API 

### ISSUE THREAD

**Issue by eunseo2** [bokzip/bokzip-backend#26]
### 필터 구현 
- category = 생활지원, 고용지원, 건강지원, 교육지원, 전체 
- sort = viewCount, starCount ( Enum Type으로 지정했기때문에 다른 값이 오면 에러남 유의) 
_**viewCount- 조회수 순 | starCount- 스크랩 순**_
- 현재 거주지 같은 경우는 데이터 정리가 필요하기 때문에 local= 혹은 아예 보내지 않아도 됨.
- 사진에서 post 21번이 viewCount가 제일 높으므로 먼저 나옴( 테스트 완료)
![image](https://user-images.githubusercontent.com/70589857/131774825-8560d0dd-0c65-4707-9ef1-5323bad09661.png)

### 조회 수 증가
일반, 중앙부처, 지역 데이터 API 요청 후 viewCount +1 증가

**Comment by hyejungg** [comment]
구현완료
